### ISSUE TITLE
How to build a flarec config.json

### ISSUE THREAD

**Issue by ZBoIsHere** [vyzo/libp2p-flare-test#5]
I am confused in how to build a flarec config.json, can you show me your config.json or config.json example.

**Comment by vyzo** [comment]
It's a simple json file that mirrors the `Config` struct:
```
{
    "Secret": "...",
    "ServerAddrTCP": "...",
    "ServerAddrUDP": "...",
    "RelayAddrTCP": "...",
    "RelayAddrUDP": "...",
    "LogzioToken": "..."
}
```

- The Secret field is the secret shared between `flarec` and `flared`.
- The Server addrs fields are the server address for TCP and UDP (QUIC).
- The Relay addrs are the limited relay address for TCP and UDP (QUIC).
- The `logzio` token is the token to upload traces to `logz.io` for data collection and analysis.

**Comment by ZBoIsHere** [comment]
Thanks for your patient explanation. another question, server means flared or the peer you want to dial?
